#EJERCICIO EN CLASE DEL DIA 28 DE ABRIL EL CUAL QUEDO PENDIENTE PARA DARLE SOLUCION SIN FUNCIONES
#JUAN CAMILO GONZALEZ DUQUE-FACULTAD INGENIERIA
#PROFESOR: YESID OSPITIA
ed=input("DIGITE SU EDAD PORFAVOR:")
eda=ed.isdigit()
while(eda==False):
    print("EL DATO QUE HAS DIGITADO NO ES UN NUMERO:" , ed)
    ed=input("DIGITE SU EDAD PORFAVOR:")
    eda=ed.isdigit()
print("GRACIAS POR SU COLABORACION, LA ENCUESTA A TERMINADO")
#NOTA: ES EL MISMO EJERCICIO PERO AL REVEZ DONDE ESCRIBES LA CADENA Y TERMINA EL PROGRAMA, DE LO CONTRARIO VOLVERA A PREGUNTAR
#ed=input("DIGITE SU EDAD PORFAVOR:")
#eda=ed.isdigit()
#while(eda):
#    print("EL DATO QUE HAS DIGITADO NO ES UN NUMERO:" , ed)
#    ed=input("DIGITE SU EDAD PORFAVOR:")
#    eda=ed.isdigit()
#print("GRACIAS POR SU COLABORACION, LA ENCUESTA A TERMINADO")
