#SOLUCION TALLER NO CALIFICABLE: REALIZADO POR JUAN CAMILO GONZALEZ DUQUE-UCC-ING. EN SISTEMAS
#ANALISIS DEL PROBLEMA:
#
#VARIABLES:
#CODIGO DEL ASOCIADO
#VALOR DEL INGRESO MENSUAL DEL ASOCIADO
#NUMERO DE AÑOS QUE LLEVA EL ASOCIADOAFILIADO A LA COOPERATIVA
#SALARIO MINIMO MENSUAL (SMM)=IMPORTANTE
#EL APORTE A LA COPERATIVA
#LA CUOTA PARA EL FONDO DE RECREACION
#LA CUOTA DE PENSION OBLIGATORIA
#
#ENTRADAS:
#CODIGO DEL ASOCIADO
#VALOR DEL INGRESO MENSUAL DEL ASOCIADO
#NUMERO DE AÑOS QUE LLEVA EL ASOCIADOAFILIADO A LA COOPERATIVA
#SALARIO MINIMO MENSUAL (SMM)=IMPORTANTE= NOTA:NO SE TOMA PROPIAMENTE PORQUE ES UN DATO QUE VAMOS A NECESITAR TODO EL TIEMPO, PERO NO SE LO VAMOS A SOLICITAR AL CLIENTE; ASI QUE NO SE VA A MOSTRAR
#
#SALIDAS:
#EL APORTE A LA COPERATIVA
#LA CUOTA PARA EL FONDO DE RECREACION
#LA CUOTA DE PENSION OBLIGATORIA
#
#
#PROCESO:
#1-VALIDACION DE LAS ENTRADAS
#
#2-EL INGRESO MENSUAL DIVIDIDO POR EL SMM (PASADO A ENTERO)
#-SI IMA ES MENOR O IGUAL A 2:
#           MOSTRAR EL MENSAJE "EL APORTE A LA COOPERATIVA DEL ASOCIADO ES DEL 1.0% DEL SMM"
#-SINO IMA ES MAYOR A 2 Y MENOR O IGUAL A 6:
#           MOSTRAR EL MENSAJE "EL APORTE A LA COOPERATIVA DEL ASOCIADO ES DEL 2.0% DEL SMM"
#SINO IMA ES MAYOR A 6:
#           MOSTRAR EL MENSAJE "EL APORTE A LA COOPERATIVA DEL ASOCIADO ES DEL 2.5% DEL SMM:" 
#DE LO CONTRARIO 
#           MOSTRAR EL MENSAJE "EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO"
#
#3-EL NUMERO DE AÑOS QUE LLEVA ASOCIADO A LA COOPERATIVA (PASADO A ENTERO)
#-SI EL ASOCIADO LLEVA 5 AÑOS O MENOS:
#           MOSTRAR EL MENSAJE "LA CUOTA DEL ASOCIADO PARA EL FONDO DE RECREACION ES DEL 0.25% DEL SMM:"
#-SINO EL ASOCIADO LLEVA MAS DE 5 AÑOS:
#            MOSTRAR EL MENSAJE "LA CUOTA DEL ASOCIADO PARA EL FONDO DE RECREACION ES DEL 0.30% DEL SMM:"
#DE LO CONTRARIO 
#           MOSTRAR EL MENSAJE "EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO"
#
#4-APORTAR AL FONDO SOLIDARIO POR VOLUNTAD DEL ASOCIADO (PASADO A ENTERO) 
#-SI EL NUMERO DIGITADO POR EL ASOCIADO ES IGUAL AL CERO (0):
#           MOSTRAR EL MENSAJE "EL ASOCIADO APORTA EL 4.0% DEL SMM AL FONDO DE SOLIDARIDAD: "
#-SINO EL NUMERO DIGITADO POR EL ASOCIADO ES IGUAL A UNO (1):
#            MOSTRAR EL MENSAJE "EL ASOCIADO NO DESEA APORTAR AL FONDO DE SOLIDARIDAD"
#DE LO CONTRARIO 
#           MOSTRAR EL MENSAJE "EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO"
#
#5-CUOTA DE LA PENSION OBLIGATORIA (PASADO A ENTERO)
#-SI IMA ES MENOR O IGUAL A 3:
#           MOSTRAR EL MENSAJE "EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 8% DEL SMM: "
#-SINO IMA ES MAYOR A 3: 
#           MOSTRAR EL MENSAJE "EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 10% DEL SMM: "
#SINO EL NUMERO DE AÑOS ASOCIADO A LA COOPERATIVA ES MAYOR O IGUAL A 10 Y IMA ES MENOR O IGUAL A 3: 
#           MOSTRAR EL MENSAJE "EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 15% DEL SMM: "
#SINO EL NUMERO DE AÑOS ASOCIADO A LA COOPERATIVA ES MAYOR O IGUAL A 10 Y IMA ES MAYOR A 3: 
#           MOSTRAR EL MENSAJE "EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 17% DEL SMM: "
#
#
#INICIO
#       nom=LEER("DIGITE EL NOMBRE DEL ASOCIADO: ")
#       cod=LEER("DIGITE EL CODIGO DEL ASOCIADO: ")
#       coda=cod.isdigit()
#       ima=LEER("DIGITE EL INGRESO MENSUAL DEL ASOCIADO, EN PESOS: ")
#       imaa=ima.isdigit()
#
#IMPRIMIR ("APORTE A LA COOPERATIVA:")
#
#SI (imaa):
#    imaa1=LEER(ima)
#    imaa12=(REDONDEAR(imaa1/737717))
#    SI (imaa12<=2):
#        aporte=(REDONDEAR(imaa1*0.01))
#        IMPRIMIR("EL APORTE A LA COOPERATIVA DEL ASOCIADO ES DEL 1.0% DEL SMM Y EQUIVALE A: " , aporte)
#    SINO imaa12>2 and imaa12<=6:
#         aporte=(REDONDEAR(imaa1*0.02))
#         IMPRIMIR("EL APORTE A LA COOPERATIVA DEL ASOCIADO ES DEL 2.0% DEL SMM Y EQUIVALE A: " , aporte)
#    SINO imaa12>6:
#         aporte=(REDONDEAR(imaa1*0.025))
#         IMPRIMIR("EL APORTE A LA COOPERATIVA DEL ASOCIADO ES DEL 2.5% DEL SMM Y EQUIVALE A: " , aporte)
#DE LO CONTRARIO:
#    IMPRIMIR("EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO" , ima )
#
#IMPRIMIR ("CUOTA PARA EL FONDO DE RECREACION:")
#
#naac=LEER("DIGITE EL NUMERO DE AÑOS QUE LLEVA EL ASOCIADO EN LA COOPERATIVA: ")
#naaca=naac.isdigit()
#
#SI (naaca):
#   nuan=int(naac)
#   SI(nuan<=5):
#       cuota=(REDONDEAR(imaa1*0.25/100))
#       IMPRIMIR("LA CUOTA DEL ASOCIADO PARA EL FONDO DE RECREACION ES DEL 0.25% DEL SMM Y EQUIVALE A:" , cuota)
#   SINO (nuan>5):
#        cuota=(REDONDEAR(imaa1*0.30/100))
#        IMPRIMIR("LA CUOTA DEL ASOCIADO PARA EL FONDO DE RECREACION ES DEL 0.30% DEL SMM Y EQUIVALE A:" , cuota)
#DE LO CONTRARIO:
#     IMPRIMIR("EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO" , naac )
#
#
#IMPRIMIR("APORTE AL FONDO DE SOLIDARIDAD ")
#
#afs=LEER("SEÑOR USUARIO SI DESEA APORTAR AL FONDO DE SOLIDARIDAD\nMARQUE CERO (0) DE LO CONTRARIO MARQUE UNO (1):")
#afsa=afs.isdigit()
#
#SI (afsa):
#    afsa1=int(afs)
#    SI (afsa1==0):
#        fondosol=(REDONDEAR(imaa1*0.04))
#        IMPRIMIR("EL ASOCIADO DECIDE APORTAR EL 4.0% DEL SMM AL FONDO DE SOLIDARIDAD Y EQUIVALE A: " , fondosol)
#    SINO (afsa1==1):
#        fondosol=(REDONDEAR(imaa1*0))
#        IMPRIMIR("EL ASOCIADO DECIDE NO APORTAR AL FONDO DE SOLIDARIDAD" , fondosol)
#DE LO CONTRARIO:
#    IMPRIMIR("EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO" , afs )
#
#IMPRIMIR("APORTE A PENSION OBLIGATORIO")
#
#
#SI (nuan>=10) Y (imaa12<=3):
#    pension=(REDONDEAR(imaa1*0.15))
#    IMPRIMIR("EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 15% DEL SMM Y EQUIVALE A: " , pension)
#SINO (nuan>=10) Y (imaa12>3):
#    pension=(REDONDEAR(imaa1*0.17))
#    IMPRIMIR("EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 17% DEL SMM Y EQUIVALE A: " , pension)
#SINO (imaa12<=3):
#    pension=(REDONDEAR(imaa1*0.08))
#    IMPRIMIR("EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 8% DEL SMM Y EQUIVALE A: " , pension)
#SINO (imaa12>3):
#    pension=(REDONDEAR(imaa1*0.1))
#    IMPRIMIR("EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 10% DEL SMM Y EQUIVALE A: " , pension)
#IMPRIMIR()
#suma=aporte+cuota+fondosol+pension
#IMPRIMIR("TOTAL NETO DE APORTES DEL ASOCIADO:" , suma) 
#
# NOMBRE DEL ASOCIADO	        CODIGO DEL ASOCIADO	INGRESO MENSUAL DEL ASOCIADO	NUMERO DE AÑOS QUE LLEVA ASOCIADO A LA COOPERATIVA	APORTA AL FONDO DE SOLIDARIDAD
#JUAN CARLOS PEREZ OROZCO	       2015	                   1500000	                                2	                                        NO=1
#TATIANA MARCELA ESPINOSA 	       2016	                   2360000	                                5	                                        SI=0
#SEBASTIAN ANDRES URQUQUI	       2017	                   4800000	                                8	                                        SI=0
#MANUEL TURIZO SANCHEZ	               2018	                   7900000	                               11 	                                        SI=0
#TANIA ARBELAEZ THOUZ	               2019	                    737717	                               10	                                        NO=1
#ISABELLA VASQUEZ FERNANDEZ	       2020	                   3855000	                                3	                                        NO=1
#EMMANUEL FERNANDEZ SUÑIGA	       2021	                   8050000	                                1	                                        NO=1
#KAROLINA SALAZAR BERMUDEZ	       2022	                   1600000	                                5	                                        SI=0
#KARMEN GOMEZ GIRALDO                  2023                        2313000                                     13                                               SI=0                  
#CARLOS ALBERTO OSPITIA                2024                         874300                                     10                                               NO=1
#JOSE ALBERTO                       VEINTE CINCO                   1543000                                      4                                               NO=1
#LUIS EDUARDO                          2026                     $DOS MILLONES                                 SIETE                                             SI=0
#LUZ MILENA                         VEINTI SEIETE               $DOS MILLONES Y MEDIO                         NUEVE                                             NO=1
#SANDRA MARINA                         2028                        3600000                                       9                                              NO=1 
nom=input("DIGITE EL NOMBRE DEL ASOCIADO: ")
cod=input("DIGITE EL CODIGO DEL ASOCIADO: ")
coda=cod.isdigit()

if (coda):
    coda1=int(cod)
else:
    print("EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO" , cod )
    
ima=input("DIGITE EL INGRESO MENSUAL DEL ASOCIADO, EN PESOS: ")
imaa=ima.isdigit()
print()
print("APORTE A LA COOPERATIVA: ")
if(imaa):
    imaa1=int(ima)
    imaa12=(imaa1/737717)
    if (imaa12<=2):
        aporte=(round(imaa1*0.01))
        print("EL APORTE A LA COOPERATIVA DEL ASOCIADO ES DEL 1.0% DEL SMM Y EQUIVALE A: " , aporte)
    elif (imaa12>2 and imaa12<=6):
        aporte=(round(imaa1*0.02))
        print("EL APORTE A LA COOPERATIVA DEL ASOCIADO ES DEL 2.0% DEL SMM Y EQUIVALE A:" , aporte)
    elif (imaa12>6):
        aporte=(round(imaa1*0.025))
        print("EL APORTE A LA COOPERATIVA DEL ASOCIADO ES DEL 2.5% DEL SMM Y EQUIVALE A:" , aporte)
else:
    if (ima):
        print("EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO:" , ima)
            
print()
print("CUOTA PARA EL FONDO DE RECREACION: ")
naac=input("DIGITE EL NUMERO DE AÑOS QUE LLEVA EL ASOCIADO EN LA COOPERATIVA: ")
naaca=naac.isdigit()

if (naaca):
    nuan=int(naac)
    if(nuan<=5):
        cuota=(round(imaa1*0.25/100))
        print("LA CUOTA DEL ASOCIADO PARA EL FONDO DE RECREACION ES DEL 0.25% DEL SMM Y EQUIVALE A:" , cuota)
    elif (nuan>5):
        cuota=(round(imaa1*0.30/100))
        print("LA CUOTA DEL ASOCIADO PARA EL FONDO DE RECREACION ES DEL 0.30% DEL SMM Y EQUIVALE A:" , cuota)
else:
     print("EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO" , naac )
print()
print("APORTE AL FONDO DE SOLIDARIDAD ")
afs=input("SEÑOR USUARIO SI DESEA APORTAR AL FONDO DE SOLIDARIDAD\nMARQUE CERO (0) DE LO CONTRARIO MARQUE UNO (1):")
afsa=afs.isdigit()

if (afsa):
    afsa1=int(afs)
    if (afsa1==0):
        fondosol=(round(imaa1*0.04))
        print("EL ASOCIADO DECIDE APORTAR EL 4.0% DEL SMM AL FONDO DE SOLIDARIDAD Y EQUIVALE A: " , fondosol)
    elif (afsa1==1):
        fondosol=(round(imaa1*0))
        print("EL ASOCIADO DECIDE NO APORTAR AL FONDO DE SOLIDARIDAD" , fondosol)
else:
    print("EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO" , afs )
print()
print("APORTE A PENSION OBLIGATORIO")
if (naaca):
    nuan=int(naac)
    if (nuan>=10) and (imaa12<=3):
        pension=(round(imaa1*0.15))
        print("EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 15% DEL SMM Y EQUIVALE A: " , pension)
    elif (nuan>=10) and (imaa12>3):
        pension=(round(imaa1*0.17))
        print("EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 17% DEL SMM Y EQUIVALE A: " , pension)
    elif (imaa12<=3):
        pension=(round(imaa1*0.08))
        print("EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 8% DEL SMM Y EQUIVALE A: " , pension)
    elif (imaa12>3):
        pension=(round(imaa1*0.1))
        print("EL APORTE A LA PENSION OBLIGATORIA DEL ASOCIADO ES DEL 10% DEL SMM Y EQUIVALE A: " , pension)
else:
    print("EL DATO QUE SE DIGITO NO ES UN NUMERO, PORFAVOR DIGITAR UN VALOR NUMERICO PARA ESTE DATO" , naac)
print()
suma=aporte+cuota+fondosol+pension
print("TOTAL NETO A PAGAR DE APORTES DEL ASOCIADO:" , suma)


#NOTA: LA FUNCION \n TE BAJA UNA LIA DEL TEXTO PARA QUE PUEDA SER VISIBLE.





















    
    


    
    
    
















































